### ISSUE TITLE
Dashboard cssclass is applied although not applied in Obsidian

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#32]
I have [this note](https://share.note.sx/rziauylr#fJUB85y39ubtyYX/3fmV1Z11WyU5CgBl4Ny3dJCag9I) I am working on:

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/8ccbed4d-798a-4992-856c-063fde25eb49)

When I upload it, the `dashboard` cssclass by Tfthacker is somehow applied (code below), and it looks like this:

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/6af8122f-e52c-421d-8378-c5d7bc6721c7)

Note, I've **never** had the dashboard cssclass applied to this particular note in Obsidian. Here's the note properties:

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/d9bb0e54-24e7-4025-9bd6-1b495f0a08fd)

I only applied it _after_ running into this issue to verify what was happening.

I also opened the uploaded .css file using developer tools, and you can see that the dashboard cssclass is in-fact applied:

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/a2b04add-042a-4958-ae45-73ae6c5212ed)

I've also had the same issue with other notes that do not have the dashboard cssclass applied.

**Dashboard css:**

```css
/* Updated 2022-02-28 */

.dashboard {
    padding-left: 25px !important;
    padding-right: 25px !important;
    padding-top: 20px !important;
}

/* Title at top of the document */
.dashboard .markdown-preview-section .title {
    top: 60px;
    position: absolute;
    font-size: 26pt !important;
    font-weight: bolder;
    letter-spacing: 8px;
}

.dashboard h1 {
    border-bottom-style: dotted !important;
    border-width: 1px !important;
    padding-bottom: 3px !important;
}

.dashboard div > ul {
    list-style: none;
    display: flex;
    column-gap: 50px;
    row-gap: 30px;
    flex-flow: row wrap;
}

.dashboard div > ul > li {
    min-width: 250px;
    width: 15%;
}
 .dashboard .markdown-preview-section {
    width: 90% !important;
    max-width: 90% !important;
 }

ul.dataview.list-view-ul {
	list-style: disc;
	display: inline-block;
}
```
